# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.0
_src_path: git@gitlab.open-net.ch:ons/ons-addons-repo-template.git
enable_ci: true
modules_name: jwt_manager,revolut_connector,security_whitelist,security_whitelist_account_budget,security_whitelist_account_journal,security_whitelist_analytic_account,security_whitelist_analytic_tag
odoo_version: 14.0
org_name: Open Net Sàrl
org_slug: ons
repo_name: Nymtech Odoo Addons
repo_slug: nymtech-addons
